//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ID_order { get; set; }
        public System.DateTime Data_order { get; set; }
        public int ID_client { get; set; }
        public int ID_equip { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Data_order1 { get; set; }
        public Nullable<int> ID_specialist { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public Nullable<int> ID_Services { get; set; }
        public Nullable<System.DateTime> Guaran { get; set; }
    
        public virtual Client_equip Client_equip { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual List_spec List_spec { get; set; }
        public virtual Services Services { get; set; }
    }
}
